export type {DefaultArgs} from "./src/types/args/defaultArgs.ts";
export type {MealServiceDietInfoArgs} from "./src/types/args/mealServiceDietInfoArgs.ts";
export {InvalidCodeError} from "./src/error/invalidCodeError.ts";
export type {BaseResponse} from "./src/types/response/baseReponse.ts";
export {MealServiceDietInfoReturn} from "./src/types/return/mealServiceDietInfoReturn.ts";
export type {SchoolInfoArgs} from "./src/types/args/schoolInfoArgs.ts";
export type {SchoolInfoInfo} from "./src/types/response/schoolInfoInfo.ts";
export type {MealServiceDietInfo} from "./src/types/response/mealServiceDietInfo.ts";
export {SchoolInfoReturn} from "./src/types/return/schoolInfoReturn.ts";
export type {AcaInsTiInfoArgs} from "./src/types/args/acaInsTiInfoArgs.ts";
export type {AcaInsTiInfoInfo} from "./src/types/response/acaInsTiInfoInfo.ts";
export {AcaInsTiInfoReturn} from "./src/types/return/acaInsTiInfoReturn.ts";
export type {SchoolScheduleArgs} from "./src/types/args/schoolScheduleArgs.ts";
export {SchoolScheduleReturn} from "./src/types/return/schoolScheduleReturn.ts";
export type {SchoolScheduleInfo} from "./src/types/response/schoolScheduleInfo.ts";
export type {HisTimetableArgs} from "./src/types/args/hisTimetableArgs.ts";
export {HisTimetableReturn} from "./src/types/return/hisTimetableReturn.ts";
export type {HisTimetableInfo} from "./src/types/response/hisTimetableInfo.ts";
export type {ClassInfoArgs} from "./src/types/args/classInfoArgs.ts";
export {ClassInfoReturn} from "./src/types/return/classInfoReturn.ts";
export type {ClassInfoInfo} from "./src/types/response/classInfoInfo.ts";
export type {ElsTimetableArgs} from "./src/types/args/elsTimetableArgs.ts";
export type {ElsTimetableInfo} from "./src/types/response/elsTimetableInfo.ts";
export {ElsTimetableReturn} from "./src/types/return/elsTimetableReturn.ts";
export type {MisTimetableInfo} from "./src/types/response/misTimetableInfo.ts";
export type {MisTimetableArgs} from "./src/types/args/misTimetableArgs.ts";
export {MisTimetableReturn} from "./src/types/return/misTimetableReturn.ts";
export type {SchoolMajorinfoArgs} from "./src/types/args/schoolMajorinfoArgs.ts";
export type {SchoolMajorinfoInfo} from "./src/types/response/schoolMajorinfoInfo.ts";
export {SchoolMajorinfoReturn} from "./src/types/return/schoolMajorinfoReturn.ts";
export type {SchulAflcoinfoArgs} from "./src/types/args/schulAflcoinfoArgs.ts";
export {SchulAflcoinfoReturn} from "./src/types/return/schulAflcoinfoReturn.ts";
export type {SchulAflcoinfoInfo} from "./src/types/response/schulAflcoinfoInfo.ts";
export type {SpsTimetableArgs} from "./src/types/args/spsTimetableArgs.ts";
export {SpsTimetableReturn} from "./src/types/return/spsTimetableReturn.ts";
export type {SpsTimetableInfo} from "./src/types/response/spsTimetableInfo.ts";
export type {TiClrminfoArgs} from "./src/types/args/tiClrminfoArgs.ts";
export type {TiClrminfoInfo} from "./src/types/response/tiClrminfoInfo.ts";
export {TiClrminfoReturn} from "./src/types/return/tiClrminfoReturn.ts";
export {Neis} from "./src/neis.ts";